### ISSUE TITLE
Prevent folder automatically opening.

### ISSUE THREAD

**Issue by tmathews** [DerrickGold/Remote-Music-Player#3]
When you are playing songs and it plays through multiple folders it opens the folders (at any depth) to show where that song is playing. This is unwanted as when on shuffle it opens every folder and makes it cumbersome to navigate. Do not open folders upon song automatic change. You will still want to close Now Playing and open file location in browse list when you click song title.

**Comment by DerrickGold** [comment]
Fixed in commit 89d7f6a
